<?php
/**
 * Code Executor
 *
 * Executes PHP code generated by AI in a safe manner.
 * MVP version: Direct execution with security validation.
 *
 * @package CreatorCore
 */

namespace CreatorCore\Executor;

defined( 'ABSPATH' ) || exit;

/**
 * Class CodeExecutor
 *
 * Safely executes AI-generated PHP code with:
 * - Security validation (forbidden functions check)
 * - Direct execution via eval()
 * - Error capture and reporting
 */
class CodeExecutor {

	/**
	 * Forbidden functions that should never be executed
	 *
	 * @var array
	 */
	private array $forbidden_functions = [
		// System execution
		'exec',
		'shell_exec',
		'system',
		'passthru',
		'popen',
		'proc_open',
		'pcntl_exec',
		'pcntl_fork',
		// Dangerous eval
		'eval',
		'assert',
		'create_function',
		// File system dangerous
		'unlink',
		'rmdir',
		'rename',
		'copy',
		'mkdir',
		'chmod',
		'chown',
		'chgrp',
		// Include/require (could include malicious files)
		'include',
		'include_once',
		'require',
		'require_once',
		// Network
		'fsockopen',
		'pfsockopen',
		'stream_socket_client',
		// Serialization
		'unserialize',
		// Output/exit
		'exit',
		'die',
		// PHP settings
		'ini_set',
		'ini_alter',
		'putenv',
		'set_include_path',
	];

	/**
	 * Execute PHP code from AI response
	 *
	 * @param string $code    PHP code to execute.
	 * @param array  $context Optional context with previous results.
	 * @return array Execution result.
	 */
	public function execute( string $code, array $context = [] ): array {
		// Validate code is not empty
		if ( empty( trim( $code ) ) ) {
			return [
				'success' => false,
				'error'   => 'Empty code provided',
			];
		}

		// Security check: validate code doesn't contain forbidden functions
		$security_check = $this->validate_code_security( $code );
		if ( ! $security_check['passed'] ) {
			return [
				'success'    => false,
				'error'      => 'Code contains forbidden functions: ' . implode( ', ', $security_check['violations'] ),
				'violations' => $security_check['violations'],
			];
		}

		// Prepare code for execution
		$prepared_code = $this->prepare_code( $code );

		// Execute the code
		return $this->execute_code( $prepared_code, $context );
	}

	/**
	 * Execute prepared PHP code
	 *
	 * @param string $code    Prepared PHP code.
	 * @param array  $context Context with previous results.
	 * @return array Execution result.
	 */
	private function execute_code( string $code, array $context = [] ): array {
		// Make context available to the code
		// phpcs:ignore WordPress.PHP.DontExtract.extract_extract
		extract( [ 'context' => $context ] );

		// Capture output
		ob_start();
		$errors = [];

		// Set custom error handler
		set_error_handler( function( $errno, $errstr, $errfile, $errline ) use ( &$errors ) {
			$errors[] = [
				'type'    => $errno,
				'message' => $errstr,
				'file'    => $errfile,
				'line'    => $errline,
			];
			return true;
		} );

		$success = false;
		$result  = null;

		try {
			// Execute the code
			// phpcs:ignore Squiz.PHP.Eval.Discouraged
			$result  = eval( $code );
			$success = true;
		} catch ( \Throwable $e ) {
			$errors[] = [
				'type'    => E_ERROR,
				'message' => $e->getMessage(),
				'file'    => $e->getFile(),
				'line'    => $e->getLine(),
			];
		}

		// Restore error handler
		restore_error_handler();
		$output = ob_get_clean();

		// Check for errors
		if ( ! $success || ! empty( $errors ) ) {
			return [
				'success' => false,
				'error'   => $errors[0]['message'] ?? 'Unknown error',
				'errors'  => $errors,
				'output'  => $output,
			];
		}

		// If result is null, consider it success (code might not return anything)
		if ( $result === null ) {
			$result = [ 'success' => true, 'output' => $output ];
		}

		return [
			'success' => true,
			'result'  => $result,
			'output'  => $output,
		];
	}

	/**
	 * Validate code security
	 *
	 * @param string $code PHP code.
	 * @return array Validation result with 'passed' and 'violations'.
	 */
	public function validate_code_security( string $code ): array {
		$violations = [];

		// Check for forbidden functions
		foreach ( $this->forbidden_functions as $func ) {
			// Match function calls: func( or func (
			$pattern = '/\b' . preg_quote( $func, '/' ) . '\s*\(/i';
			if ( preg_match( $pattern, $code ) ) {
				$violations[] = $func;
			}
		}

		// Check for preg_replace with /e modifier (deprecated but dangerous)
		if ( preg_match( '/preg_replace\s*\([^,]+\/[^\/]*e[^\/]*\//', $code ) ) {
			$violations[] = 'preg_replace with /e modifier';
		}

		// Check for backticks (shell execution)
		if ( preg_match( '/`[^`]+`/', $code ) ) {
			$violations[] = 'backtick shell execution';
		}

		// Check for dangerous SQL patterns
		if ( preg_match( '/\b(DROP|TRUNCATE|DELETE\s+FROM)\s+(TABLE|DATABASE)/i', $code ) ) {
			$violations[] = 'dangerous SQL statement';
		}

		return [
			'passed'     => empty( $violations ),
			'violations' => $violations,
		];
	}

	/**
	 * Prepare code for execution
	 *
	 * @param string $code Original code.
	 * @return string Prepared code for eval().
	 */
	private function prepare_code( string $code ): string {
		// Remove opening/closing PHP tags
		$code = preg_replace( '/^<\?php\s*/', '', trim( $code ) );
		$code = preg_replace( '/\?>\s*$/', '', $code );

		return trim( $code );
	}
}
